# -*- coding: utf-8 -*-
"""ResNet18-TL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gnm_ItZ1fr4PZBglKOJoJ45bXXaEgpOf
"""

# Cell 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Cell 2: Extract Dataset
import zipfile
import os

zip_path = '/content/drive/My Drive/DataSet.zip'
output_dir = '/content/dataset/'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(output_dir)

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, ConcatDataset
from torchvision import datasets, transforms, models
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

data_transforms = {
    'train': transforms.Compose([
        transforms.RandomResizedCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]),
    'val': transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]),
    'test': transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ]),
}

dataset_base_path = '/content/dataset/DataSet'
species_folders = ['Apple', 'CASAVA', 'Corn', 'Grape', 'Potato']

# Initialize lists to store datasets
train_datasets = []
val_datasets = []
test_datasets = []

# Create a mapping for class names to indices
all_classes = []
class_to_species = {}
global_class_idx = 0

# First pass: collect all class names and create mapping
for species in species_folders:
    species_path = os.path.join(dataset_base_path, species)
    train_dir = os.path.join(species_path, 'Train')

    if os.path.exists(train_dir):
        temp_dataset = datasets.ImageFolder(train_dir)
        for class_name in temp_dataset.classes:
            full_class_name = f"{species}_{class_name}"
            all_classes.append(full_class_name)
            class_to_species[full_class_name] = species
            global_class_idx += 1

print(f"Total classes found: {len(all_classes)}")
print("Classes:", all_classes)

# Second pass: load datasets with proper class mapping
for species in species_folders:
    species_path = os.path.join(dataset_base_path, species)
    train_dir = os.path.join(species_path, 'Train')
    val_dir = os.path.join(species_path, 'Validate')
    test_dir = os.path.join(species_path, 'Test')

    if all(os.path.exists(d) for d in [train_dir, val_dir, test_dir]):
        # Load datasets
        train_dataset = datasets.ImageFolder(train_dir, transform=data_transforms['train'])
        val_dataset = datasets.ImageFolder(val_dir, transform=data_transforms['val'])
        test_dataset = datasets.ImageFolder(test_dir, transform=data_transforms['test'])

        # Remap class indices to global indices
        species_to_global_mapping = {}
        for local_idx, class_name in enumerate(train_dataset.classes):
            full_class_name = f"{species}_{class_name}"
            global_idx = all_classes.index(full_class_name)
            species_to_global_mapping[local_idx] = global_idx

        # Create custom datasets with remapped labels
        class RemappedDataset(torch.utils.data.Dataset):
            def __init__(self, original_dataset, label_mapping):
                self.original_dataset = original_dataset
                self.label_mapping = label_mapping

            def __len__(self):
                return len(self.original_dataset)

            def __getitem__(self, idx):
                image, label = self.original_dataset[idx]
                new_label = self.label_mapping[label]
                return image, new_label

        # Create remapped datasets
        train_remapped = RemappedDataset(train_dataset, species_to_global_mapping)
        val_remapped = RemappedDataset(val_dataset, species_to_global_mapping)
        test_remapped = RemappedDataset(test_dataset, species_to_global_mapping)

        train_datasets.append(train_remapped)
        val_datasets.append(val_remapped)
        test_datasets.append(test_remapped)

        print(f"Loaded {species}: Train={len(train_dataset)}, Val={len(val_dataset)}, Test={len(test_dataset)}")

# Combine all datasets
combined_train = ConcatDataset(train_datasets)
combined_val = ConcatDataset(val_datasets)
combined_test = ConcatDataset(test_datasets)

# Create DataLoaders
train_loader = DataLoader(combined_train, batch_size=32, shuffle=True)
val_loader = DataLoader(combined_val, batch_size=32, shuffle=False)
test_loader = DataLoader(combined_test, batch_size=32, shuffle=False)

print(f"\nFinal dataset sizes:")
print(f"Train: {len(combined_train)}")
print(f"Validation: {len(combined_val)}")
print(f"Test: {len(combined_test)}")

model = models.resnet18(pretrained=True)

# Freeze all layers except the final fully connected layer
for param in model.parameters():
    param.requires_grad = False

# Modify the final layer
num_classes = len(all_classes)
model.fc = nn.Linear(model.fc.in_features, num_classes)

# Move to device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
print(f"Using device: {device}")
print(f"Model has {num_classes} output classes")

criterion = nn.CrossEntropyLoss()  # LOSS FUNCTION - CrossEntropyLoss includes softmax activation
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)

num_epochs = 30

# Lists to store training history for plotting
train_losses = []
train_accuracies = []
val_losses = []
val_accuracies = []

for epoch in range(num_epochs):
    # Training phase
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)  # ResNet-18 uses ReLU ACTIVATION FUNCTIONS internally
        loss = criterion(outputs, labels)  # CrossEntropyLoss applies softmax + negative log likelihood
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = correct / total

    # Validation phase
    model.eval()
    val_running_loss = 0.0
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_running_loss += loss.item()

            _, predicted = torch.max(outputs, 1)
            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

    val_loss = val_running_loss / len(val_loader)
    val_accuracy = val_correct / val_total

    # Store values for plotting
    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_accuracy)
    val_losses.append(val_loss)
    val_accuracies.append(val_accuracy)

    print(f"Epoch {epoch+1}/{num_epochs} => "
          f"Train Loss: {epoch_loss:.4f}, Train Accuracy: {epoch_accuracy:.4f} | "
          f"Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_accuracy:.4f}")

# Plot Training History
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

# Plot Loss
ax1.plot(range(1, num_epochs + 1), train_losses, 'b-', label='Training Loss')
ax1.plot(range(1, num_epochs + 1), val_losses, 'r-', label='Validation Loss')
ax1.set_title('Training and Validation Loss Over Epochs')
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Loss')
ax1.legend()
ax1.grid(True)

# Plot Accuracy
ax2.plot(range(1, num_epochs + 1), train_accuracies, 'b-', label='Training Accuracy')
ax2.plot(range(1, num_epochs + 1), val_accuracies, 'r-', label='Validation Accuracy')
ax2.set_title('Training and Validation Accuracy Over Epochs')
ax2.set_xlabel('Epoch')
ax2.set_ylabel('Accuracy')
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.show()

model.eval()
all_preds = []
all_labels = []

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Generate classification report
report = classification_report(all_labels, all_preds, target_names=all_classes, output_dict=True)

# Calculate individual class accuracies
def calculate_class_accuracy(y_true, y_pred, class_idx):
    """Calculate accuracy for a specific class"""
    class_mask = (np.array(y_true) == class_idx)
    if np.sum(class_mask) == 0:
        return 0.0
    class_predictions = np.array(y_pred)[class_mask]
    class_true = np.array(y_true)[class_mask]
    return np.sum(class_predictions == class_true) / len(class_true)

# Create detailed results table with accuracy
results_data = []
for i, class_name in enumerate(all_classes):
    if class_name in report:
        species = class_to_species[class_name]
        subclass = class_name.replace(f"{species}_", "")

        precision = report[class_name]['precision'] * 100
        recall = report[class_name]['recall'] * 100
        f1_score = report[class_name]['f1-score'] * 100
        support = report[class_name]['support']

        # Calculate individual class accuracy
        class_accuracy = calculate_class_accuracy(all_labels, all_preds, i) * 100

        results_data.append({
            'Species': species,
            'Subclass': subclass,
            'Accuracy (%)': f"{class_accuracy:.2f}",
            'Precision (%)': f"{precision:.2f}",
            'Recall (%)': f"{recall:.2f}",
            'F1-Score (%)': f"{f1_score:.2f}",
            'Support': support
        })

# Create DataFrame and display results
results_df = pd.DataFrame(results_data)

print("\n" + "="*90)
print("DETAILED SUBCLASS CLASSIFICATION RESULTS (WITH INDIVIDUAL ACCURACY)")
print("="*90)

# Group by species and display
for species in species_folders:
    species_data = results_df[results_df['Species'] == species]
    if not species_data.empty:
        print(f"\n{species.upper()}:")
        print("-" * 80)
        for _, row in species_data.iterrows():
            print(f"{row['Subclass']:<25} | Accuracy: {row['Accuracy (%)']}% | "
                  f"Precision: {row['Precision (%)']}% | Recall: {row['Recall (%)']}% | "
                  f"F1-Score: {row['F1-Score (%)']}% | Support: {row['Support']}")

# Overall accuracy
overall_accuracy = report['accuracy'] * 100
print(f"\nOVERALL ACCURACY: {overall_accuracy:.2f}%")

# Create a summary table
print("\n" + "="*90)
print("SUMMARY TABLE")
print("="*90)
print(f"{'Species':<12} {'Subclass':<25} {'Accuracy':<10} {'Precision':<10} {'Recall':<10} {'F1-Score':<10} {'Support':<8}")
print("-" * 90)
for _, row in results_df.iterrows():
    print(f"{row['Species']:<12} {row['Subclass']:<25} {row['Accuracy (%)']:<10} "
          f"{row['Precision (%)']:<10} {row['Recall (%)']:<10} {row['F1-Score (%)']:<10} {row['Support']:<8}")

# Print traditional classification report
print("\n" + "="*90)
print("TRADITIONAL CLASSIFICATION REPORT")
print("="*90)
print(classification_report(all_labels, all_preds, target_names=all_classes))

plt.figure(figsize=(15, 12))
cm = confusion_matrix(all_labels, all_preds)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=all_classes, yticklabels=all_classes)
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix - All Subclasses')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 3, figsize=(18, 12))
axes = axes.flatten()

for idx, species in enumerate(species_folders):
    if idx < len(axes):
        # Get indices for this species
        species_classes = [i for i, cls in enumerate(all_classes) if cls.startswith(species)]

        if species_classes:
            # Extract submatrix for this species
            species_cm = cm[np.ix_(species_classes, species_classes)]
            species_labels = [all_classes[i].replace(f"{species}_", "") for i in species_classes]

            sns.heatmap(species_cm, annot=True, fmt='d', cmap='Blues',
                       xticklabels=species_labels, yticklabels=species_labels,
                       ax=axes[idx])
            axes[idx].set_title(f'{species} Confusion Matrix')
            axes[idx].set_xlabel('Predicted')
            axes[idx].set_ylabel('True')

# Hide unused subplot
if len(species_folders) < len(axes):
    axes[-1].set_visible(False)

plt.tight_layout()
plt.show()